"""Add listing_type column and index

Revision ID: 0a35463efb90
Revises: 994501de2863
Create Date: 2025-04-19 23:02:02.149215

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a35463efb90"
down_revision: Union[str, None] = "994501de2863"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("listings", sa.Column("listing_type", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_listings_listing_type"), "listings", ["listing_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listings_listing_type"), table_name="listings")
    op.drop_column("listings", "listing_type")
    # ### end Alembic commands ###
