"""create listings table

Revision ID: 994501de2863
Revises:
Create Date: 2025-04-19 09:58:19.504485

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "994501de2863"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.String(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("area", sa.String(), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Integer(), nullable=True),
        sa.Column("house_type", sa.String(), nullable=True),
        sa.Column("posted_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("amenities", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "scraped_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_listings_id"), "listings", ["id"], unique=False)
    op.create_index(
        op.f("ix_listings_listing_id"), "listings", ["listing_id"], unique=True
    )
    op.create_index(
        op.f("ix_listings_posted_date"), "listings", ["posted_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listings_posted_date"), table_name="listings")
    op.drop_index(op.f("ix_listings_listing_id"), table_name="listings")
    op.drop_index(op.f("ix_listings_id"), table_name="listings")
    op.drop_table("listings")
    # ### end Alembic commands ###
