# === Paths ===
data_dir: "data/"
raw_data_dir: "data/raw/"
processed_data_dir: "data/processed/"
failed_data_dir: "data/raw/failed_data/"
logs_dir: "logs/"

# === Scraper Settings ===
base_url: "https://jiji.com.gh/houses-apartments-for-rent"
scroll_count: 1
headless: true

# === Database Settings ===
table_name: raw_listings
