
# === General App Settings ===
app_port: 8000
app_env: development
use_thread: True

# === Directory Paths ===
data_dir: data/
raw_data_dir: data/raw/
processed_data_dir: data/processed/
model_dir: models/
metrics_dir: data/monitoring/reports

# === Scraper Settings ===
base_url: https://jiji.com.gh/houses-apartments-for-rent
scroll_count: 1
headless: true
table_name: raw_listings
