
# === General App Settings ===
app_port: 8000
app_env: development

# === Directory Paths ===
data_dir: data/
model_dir: models/
metrics_dir: data/monitoring/reports

# === File Paths ===
db_path: data/rentals.db

# === Scraper Settings ===
base_url: https://jiji.com.gh/houses-apartments-for-rent
scroll_count: 2
headless: false
table_name: raw_listings
